###
GET http://localhost:5000/api/credentials HTTP/1.1

### Request a single credential
GET http://localhost:5000/api/credentials/MyService HTTP/1.1
Content-Type: Application/json


### Add a new credential
POST http://localhost:5000/api/credentials HTTP/1.1
Content-Type: application/json

{
  "service": "Hello",
  "username": "Hello",
  "password": "Hello"
}
### Delete a credential
DELETE /api/credentials/MyService HTTP/1.1
